### ISSUE TITLE
Choix outil de création UML

### ISSUE THREAD

**Issue by caronpe** [TL1-fa17/projet2#2]
Création de l'UML du programme Labyrinth Grace à l'outils colaboratif Cacoo

**Comment by caronpe** [comment]
L'outil est à tester, je sais pas si c'est le meilleur choix! (mais bon je sais pas si c'est ma vieille version de firefox qui me bloque ou si la gestion des Attributs est buggé)

**Comment by cdlm** [comment]
Au besoin, je sais que des collègues utilisent https://genmymodel.com

**Comment by florentvitse** [comment]
Je viens de créer un diagramme sur ce site et je vous ai ajouter (PE & Étienne) via un mail sur le site de l'école.
Pour vous inscrire, il existe un couplage avec GitHub justement :)

**Comment by e-adriansen** [comment]
Exception in thread "main" java.lang.RuntimeException: Resource not found: testdata/alphamap.png 

J'ai de nouveau cette erreur à l’exécution deWindowGame.java, pourtant je n'ai changé depuis le cours d'hier. 




Fri Feb 20 14:06:43 CET 2015 INFO:Slick Build #237 
Fri Feb 20 14:06:43 CET 2015 INFO:LWJGL Version: 2.9.2 
Fri Feb 20 14:06:43 CET 2015 INFO:OriginalDisplayMode: 1280 x 1024 x 32 @60Hz 
Fri Feb 20 14:06:43 CET 2015 INFO:TargetDisplayMode: 800 x 600 x 0 @0Hz 
Fri Feb 20 14:06:43 CET 2015 INFO:Starting display 800x600 
Fri Feb 20 14:06:43 CET 2015 INFO:Use Java PNG Loader = true 
WARNING: Found unknown Windows version: Windows 7 
Attempting to use default windows plug-in. 
Loading: net.java.games.input.DirectAndRawInputEnvironmentPlugin 
Fri Feb 20 14:06:43 CET 2015 INFO:Found 0 controllers 
Exception in thread "main" java.lang.RuntimeException: Resource not found: testdata/alphamap.png 
at org.newdawn.slick.util.ResourceLoader.getResourceAsStream(ResourceLoader.java:69) 
at org.newdawn.slick.opengl.InternalTextureLoader.getTexture(InternalTextureLoader.java:185) 
at org.newdawn.slick.Image.<init>(Image.java:192) 
at org.newdawn.slick.Image.<init>(Image.java:166) 
at org.newdawn.slick.Image.<init>(Image.java:154) 
at org.newdawn.slick.Image.<init>(Image.java:132) 
at org.newdawn.slick.tests.AlphaMapTest.init(AlphaMapTest.java:33) 
at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:393) 
at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:317) 
at org.newdawn.slick.tests.AlphaMapTest.main(AlphaMapTest.java:79)
